<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Joshua Loftus">

<title>Week 2 seminar (complete)</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="notebook2_complete_files/libs/clipboard/clipboard.min.js"></script>
<script src="notebook2_complete_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="notebook2_complete_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="notebook2_complete_files/libs/quarto-html/popper.min.js"></script>
<script src="notebook2_complete_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="notebook2_complete_files/libs/quarto-html/anchor.min.js"></script>
<link href="notebook2_complete_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="notebook2_complete_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="notebook2_complete_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="notebook2_complete_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="notebook2_complete_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#before-the-seminar" id="toc-before-the-seminar" class="nav-link active" data-scroll-target="#before-the-seminar">Before the seminar</a></li>
  <li><a href="#problems" id="toc-problems" class="nav-link" data-scroll-target="#problems">Problems</a>
  <ul class="collapse">
  <li><a href="#optional-can-be-done-at-home" id="toc-optional-can-be-done-at-home" class="nav-link" data-scroll-target="#optional-can-be-done-at-home">Optional, can be done at home</a></li>
  </ul></li>
  <li><a href="#coding" id="toc-coding" class="nav-link" data-scroll-target="#coding">Coding</a>
  <ul class="collapse">
  <li><a href="#matrices-and-vectors-in-r" id="toc-matrices-and-vectors-in-r" class="nav-link" data-scroll-target="#matrices-and-vectors-in-r">1. Matrices and vectors in R</a></li>
  <li><a href="#regression-on-real-data" id="toc-regression-on-real-data" class="nav-link" data-scroll-target="#regression-on-real-data">2. Regression on real data</a></li>
  <li><a href="#partialling-out-and-the-omitted-variable" id="toc-partialling-out-and-the-omitted-variable" class="nav-link" data-scroll-target="#partialling-out-and-the-omitted-variable">3. Partialling out, and the omitted variable</a></li>
  <li><a href="#regression-models-with-simulated-data" id="toc-regression-models-with-simulated-data" class="nav-link" data-scroll-target="#regression-models-with-simulated-data">4. Regression models with simulated data</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Week 2 seminar (complete)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Joshua Loftus </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<!-- Teacher version. This file is shown on screen in the seminar, so nothing in it
is addressed to the teacher except this comment. Boxes: blue "Hint 1, 2, ..." and
green "Reveal solution/answer", all collapsed; click to open. Hints are revealed in
order, after the room has had a few minutes, the solution last. Hints and solutions
carrying the class .answer are removed from the student file notebook2.qmd by
_build_env/make_incomplete.py; hints without it (the pre-seminar exercises and the
optional problems) stay in the student file, behind a warning not to open them
early. Do not edit the student file by hand, and do not release this file.

How this seminar runs (3 October): students do exercises 1 to 3 at home (3 redoes
the lecture's proof and is not gone through in the room). In the
room: problems 1 and 2 (about 20 minutes, hints then answers), then the coding
(about 35). Everything headed "Optional, can be done at home" is outside the
seminar. If the room runs slow, protect problem 2 and coding part 3. -->
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)      <span class="co"># should've already install.packages("tidyverse")</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gapminder)      <span class="co"># might need to install.packages("gapminder")</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)          <span class="co"># might need to install.packages("broom")</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins) <span class="co"># might need to install.packages("palmerpenguins")</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)         <span class="co"># might need to install.packages("GGally")</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">theme_set</span>(<span class="fu">theme_minimal</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="before-the-seminar" class="level2">
<h2 class="anchored" data-anchor-id="before-the-seminar">Before the seminar</h2>
<!-- At home, before the seminar. -->
<p>The lecture stated two results and left their proofs to you (exercises 1 and 2), and proved a third, which you redo with the slides closed (exercise 3). Do all three on paper before the seminar; the seminar’s problems are variations on the first two. You may use, without proof, two facts about conditional expectation from ST102: the tower property, <span class="math inline">\(\mathbb E[Z] = \mathbb E\big[\mathbb E[Z \mid X]\big]\)</span>, and taking out what is known, <span class="math inline">\(\mathbb E[g(X)\, Z \mid X] = g(X)\, \mathbb E[Z \mid X]\)</span> for any function <span class="math inline">\(g\)</span> of <span class="math inline">\(X\)</span> (given <span class="math inline">\(X\)</span>, a function of <span class="math inline">\(X\)</span> is a constant).</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Hints">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Hints
</div>
</div>
<div class="callout-body-container callout-body">
<p>Each exercise has hints, collapsed below it. Do not open a hint unless you have been stuck for at least a few minutes, and open them in order. The solutions are revealed in the seminar.</p>
</div>
</div>
<p><strong>Exercise 1 (optimal model theorem).</strong> Let <span class="math inline">\(\mathbb E Y^2 &lt; \infty\)</span>, <span class="math inline">\(f^\star(x) = \mathbb E[Y \mid X = x]\)</span> and <span class="math inline">\(R(f) = \mathbb E\big[(Y - f(X))^2\big]\)</span>. Show that for every <span class="math inline">\(f\)</span> with <span class="math inline">\(\mathbb E f(X)^2 &lt; \infty\)</span>, <span class="math display">\[
R(f) = R(f^\star) + \mathbb E\big[(f^\star(X) - f(X))^2\big].
\]</span> Conclude that <span class="math inline">\(f^\star\)</span> has the smallest risk of all functions of <span class="math inline">\(X\)</span>, and that the excess risk of any <span class="math inline">\(f\)</span>, fitted by any method, is the one number <span class="math inline">\(\mathbb E[(f^\star(X) - f(X))^2]\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 1">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Add and subtract <span class="math inline">\(f^\star(X)\)</span> inside the square, then expand.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 2">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Show that the cross term, <span class="math inline">\(\mathbb E\big[(Y - f^\star(X))\,(f^\star(X) - f(X))\big]\)</span>, is zero.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 3">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Condition on <span class="math inline">\(X\)</span> first (the tower property), then take out what is known.</p>
</div>
</div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Hints 1 to 3 in order. Expanding <span class="math inline">\(Y - f(X) = \big(Y - f^\star(X)\big) + \big(f^\star(X) - f(X)\big)\)</span>: <span class="math display">\[
R(f) = R(f^\star) + \mathbb E\big[(f^\star(X) - f(X))^2\big] + 2\,\mathbb E\big[(Y - f^\star(X))\,(f^\star(X) - f(X))\big].
\]</span> The cross term vanishes because <span class="math inline">\(g(X) = f^\star(X) - f(X)\)</span> is a function of <span class="math inline">\(X\)</span>: <span class="math display">\[
\mathbb E\big[(Y - f^\star(X))\,g(X)\big] = \mathbb E\Big[g(X)\,\mathbb E\big[Y - f^\star(X) \mid X\big]\Big] = 0,
\]</span> by the tower property, then taking out what is known, then <span class="math inline">\(\mathbb E[Y \mid X] = f^\star(X)\)</span>, the definition of <span class="math inline">\(f^\star\)</span>. (Square-integrability makes every expectation finite; Cauchy-Schwarz for the cross term.) Hence <span class="math inline">\(R(f) - R(f^\star) = \mathbb E[(f^\star(X) - f(X))^2] \ge 0\)</span>, with equality only when <span class="math inline">\(f(X) = f^\star(X)\)</span> with probability one. <span class="math inline">\(\blacksquare\)</span></p>
<p>The fact that does the work: a residual against the conditional mean, <span class="math inline">\(Y - f^\star(X)\)</span>, is orthogonal to every function of <span class="math inline">\(X\)</span>. It is the same first move as week 1’s bias-variance decomposition, and the cross term dies for the same reason.</p>
<p>Common errors: taking <span class="math inline">\(f^\star(X)\)</span> outside an expectation without conditioning first; writing <span class="math inline">\(\mathbb E[Y - f^\star(X)] = 0\)</span>, which is true but not enough (the cross term needs the conditional version, <span class="math inline">\(\mathbb E[Y - f^\star(X) \mid X] = 0\)</span>, because <span class="math inline">\(g(X)\)</span> is random); assuming <span class="math inline">\(f\)</span> is linear. The theorem needs no linearity, which is the point of it.</p>
</div>
</div>
</div>
<p><strong>Exercise 2 (omitted-variable bias).</strong> Two predictors matter: <span class="math inline">\(\mathbf y = \beta_1 \mathbf x_1 + \beta_2 \mathbf x_2 + \boldsymbol\varepsilon\)</span>, all vectors in <span class="math inline">\(\mathbb R^n\)</span> and centered (the intercept partialled out, as in the lecture). What is fixed: the inputs <span class="math inline">\(\mathbf x_1\)</span> and <span class="math inline">\(\mathbf x_2\)</span>, which we condition on. What is random: the noise, with <span class="math inline">\(\mathbb E\,\boldsymbol\varepsilon = \mathbf 0\)</span>, and through it <span class="math inline">\(\mathbf y\)</span>. Somebody regresses <span class="math inline">\(\mathbf y\)</span> on <span class="math inline">\(\mathbf x_1\)</span> alone and reports <span class="math inline">\(\hat\beta_{\text{short}} = \mathbf x_1^\top\mathbf y / \mathbf x_1^\top\mathbf x_1\)</span>, random through <span class="math inline">\(\mathbf y\)</span>. Show that <span class="math display">\[
\mathbb E\big[\hat\beta_{\text{short}} \mid \mathbf x_1, \mathbf x_2\big] = \beta_1 + \beta_2\,\hat\delta, \qquad \hat\delta = \frac{\mathbf x_1^\top\mathbf x_2}{\mathbf x_1^\top\mathbf x_1},
\]</span> say in words what <span class="math inline">\(\hat\delta\)</span> is, and say why it carries no randomness. When is the short regression unbiased for <span class="math inline">\(\beta_1\)</span>?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 1">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Substitute the model for <span class="math inline">\(\mathbf y\)</span> inside <span class="math inline">\(\mathbf x_1^\top\mathbf y\)</span> and split the fraction into three terms.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 2">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Two of the three terms are numbers once the inputs are fixed. Only the noise term is random: what is its expectation given the inputs?</p>
</div>
</div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Hint 1: <span class="math inline">\(\mathbf x_1^\top\mathbf y = \beta_1\,\mathbf x_1^\top\mathbf x_1 + \beta_2\,\mathbf x_1^\top\mathbf x_2 + \mathbf x_1^\top\boldsymbol\varepsilon\)</span>, so <span class="math display">\[
\hat\beta_{\text{short}} = \beta_1 + \beta_2\,\hat\delta + \frac{\mathbf x_1^\top\boldsymbol\varepsilon}{\mathbf x_1^\top\mathbf x_1}.
\]</span> Hint 2: conditioning on the inputs, the last term has expectation <span class="math inline">\(\mathbf x_1^\top\,\mathbb E[\boldsymbol\varepsilon \mid \mathbf x_1, \mathbf x_2] / \mathbf x_1^\top\mathbf x_1 = 0\)</span>; the noise is mean zero given the inputs, and this is the one place the randomness enters. <span class="math inline">\(\blacksquare\)</span></p>
<p><span class="math inline">\(\hat\delta\)</span> is the least-squares slope of <span class="math inline">\(\mathbf x_2\)</span> on <span class="math inline">\(\mathbf x_1\)</span> in these inputs (through the origin, which for centered vectors is the slope with an intercept): units of <span class="math inline">\(x_2\)</span> per unit of <span class="math inline">\(x_1\)</span>, a regression slope and not a correlation. It is a function of the fixed inputs only, so once they are given it is a number; the hat records that it is computed from data, not that it is random (contrast <span class="math inline">\(\hat\beta_{\text{short}}\)</span>, which is random through <span class="math inline">\(\mathbf y\)</span>). The bias <span class="math inline">\(\beta_2\hat\delta\)</span> is zero when the left-out variable does not matter (<span class="math inline">\(\beta_2 = 0\)</span>) or is orthogonal to the kept one (<span class="math inline">\(\hat\delta = 0\)</span>, uncorrelated after centering); otherwise it has either sign and can be larger than <span class="math inline">\(\beta_1\)</span> itself.</p>
<p>Common errors: using <span class="math inline">\(\mathbf x_1^\top\mathbf x_2\)</span> for raw vectors when an intercept is fitted (the formula is then about the wrong regression); reading <span class="math inline">\(\hat\delta\)</span> as a correlation; “the bias is <span class="math inline">\(\beta_2\)</span>”, forgetting <span class="math inline">\(\hat\delta\)</span>; treating <span class="math inline">\(\boldsymbol\varepsilon\)</span> as zero rather than mean zero (the expectation is needed here; the exact in-sample version is problem 2); writing <span class="math inline">\(\mathbb E\,\hat\beta_{\text{short}}\)</span> without saying what is being averaged over (the noise, with the inputs held fixed).</p>
</div>
</div>
</div>
<p><strong>Exercise 3 (partialling-out theorem).</strong> The lecture proved this one. Close the slides and prove it again. <span class="math inline">\(\mathbf X = [\mathbf X_1 \;\; \mathbf x_2]\)</span> has full column rank, with the intercept column inside <span class="math inline">\(\mathbf X_1\)</span>; <span class="math inline">\(\mathbf M_1 = \mathbf I - \mathbf X_1(\mathbf X_1^\top\mathbf X_1)^{-1}\mathbf X_1^\top\)</span> and <span class="math inline">\(\tilde{\mathbf x}_2 = \mathbf M_1\mathbf x_2\)</span>. You may use that <span class="math inline">\(\mathbf M_1\)</span> is symmetric, that <span class="math inline">\(\mathbf M_1^2 = \mathbf M_1\)</span> and that <span class="math inline">\(\mathbf M_1\mathbf X_1 = \mathbf 0\)</span> (optional problem 4 proves all three). Show that the coefficient on <span class="math inline">\(\mathbf x_2\)</span> in the least-squares regression of <span class="math inline">\(\mathbf y\)</span> on <span class="math inline">\(\mathbf X\)</span> is <span class="math display">\[
\hat\beta_2 = \frac{\tilde{\mathbf x}_2^\top \mathbf y}{\tilde{\mathbf x}_2^\top \tilde{\mathbf x}_2},
\]</span> and that regressing <span class="math inline">\(\tilde{\mathbf y} = \mathbf M_1\mathbf y\)</span> on <span class="math inline">\(\tilde{\mathbf x}_2\)</span> gives the same number. Where is full column rank used?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 1">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Start from the full regression and its normal equations: <span class="math inline">\(\mathbf y = \mathbf X_1\hat{\boldsymbol\beta}_1 + \mathbf x_2\hat\beta_2 + \mathbf r\)</span>, with <span class="math inline">\(\mathbf X_1^\top\mathbf r = \mathbf 0\)</span> and <span class="math inline">\(\mathbf x_2^\top\mathbf r = 0\)</span>. Which matrix removes the <span class="math inline">\(\mathbf X_1\)</span> term?</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 2">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Multiply through by <span class="math inline">\(\mathbf M_1\)</span> and say what happens to each of the three terms on the right. For the last one, write <span class="math inline">\(\mathbf M_1\mathbf r = \mathbf r - \mathbf X_1(\mathbf X_1^\top\mathbf X_1)^{-1}\mathbf X_1^\top\mathbf r\)</span>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 3">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 3
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>You now have <span class="math inline">\(\mathbf M_1\mathbf y = \tilde{\mathbf x}_2\,\hat\beta_2 + \mathbf r\)</span>: a vector equation with one unknown number. Multiply by a row vector that turns it into a scalar equation in which the coefficient of <span class="math inline">\(\hat\beta_2\)</span> is positive.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 4">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 4
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>After multiplying by <span class="math inline">\(\tilde{\mathbf x}_2^\top = \mathbf x_2^\top\mathbf M_1\)</span>, two things remain: the term <span class="math inline">\(\tilde{\mathbf x}_2^\top\mathbf r\)</span>, and an extra <span class="math inline">\(\mathbf M_1\)</span> on the left side. Each goes away by one of the properties of <span class="math inline">\(\mathbf M_1\)</span> you were given.</p>
</div>
</div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The lecture’s six lines. Hint 1 is the start. Hint 2: <span class="math inline">\(\mathbf M_1\mathbf y = \mathbf M_1\mathbf X_1\hat{\boldsymbol\beta}_1 + \mathbf M_1\mathbf x_2\hat\beta_2 + \mathbf M_1\mathbf r\)</span>, where <span class="math inline">\(\mathbf M_1\mathbf X_1 = \mathbf 0\)</span>, <span class="math inline">\(\mathbf M_1\mathbf x_2 = \tilde{\mathbf x}_2\)</span> by definition, and <span class="math inline">\(\mathbf M_1\mathbf r = \mathbf r\)</span> because <span class="math inline">\(\mathbf X_1^\top\mathbf r = \mathbf 0\)</span> (the residual is already in the orthogonal complement of <span class="math inline">\(\mathrm{col}(\mathbf X_1)\)</span>). So <span class="math display">\[
\mathbf M_1\mathbf y = \tilde{\mathbf x}_2\,\hat\beta_2 + \mathbf r.
\]</span> Hint 3: multiply by <span class="math inline">\(\tilde{\mathbf x}_2^\top\)</span>: <span class="math display">\[
\tilde{\mathbf x}_2^\top\mathbf M_1\mathbf y = \tilde{\mathbf x}_2^\top\tilde{\mathbf x}_2\,\hat\beta_2 + \tilde{\mathbf x}_2^\top\mathbf r.
\]</span> Hint 4, in two steps. <strong>Symmetry moves <span class="math inline">\(\mathbf M_1\)</span> across an inner product</strong>: <span class="math inline">\(\tilde{\mathbf x}_2^\top\mathbf r = \mathbf x_2^\top\mathbf M_1\mathbf r = \mathbf x_2^\top\mathbf r = 0\)</span>, the last normal equation. <strong>Idempotence removes the extra <span class="math inline">\(\mathbf M_1\)</span></strong>: <span class="math inline">\(\tilde{\mathbf x}_2^\top\mathbf M_1\mathbf y = \mathbf x_2^\top\mathbf M_1\mathbf M_1\mathbf y = \mathbf x_2^\top\mathbf M_1\mathbf y = \tilde{\mathbf x}_2^\top\mathbf y\)</span>. Hence <span class="math inline">\(\tilde{\mathbf x}_2^\top\mathbf y = \tilde{\mathbf x}_2^\top\tilde{\mathbf x}_2\,\hat\beta_2\)</span>. Full column rank is used twice: it makes <span class="math inline">\(\mathbf X_1^\top\mathbf X_1\)</span> invertible, so that <span class="math inline">\(\mathbf M_1\)</span> is defined, and it makes <span class="math inline">\(\tilde{\mathbf x}_2 \ne \mathbf 0\)</span> (otherwise <span class="math inline">\(\mathbf x_2 = \mathbf X_1(\mathbf X_1^\top\mathbf X_1)^{-1}\mathbf X_1^\top\mathbf x_2\)</span> would be a combination of the columns of <span class="math inline">\(\mathbf X_1\)</span>), so <span class="math inline">\(\tilde{\mathbf x}_2^\top\tilde{\mathbf x}_2 &gt; 0\)</span> and we may divide. <span class="math inline">\(\blacksquare\)</span></p>
<p>Residual on residual: the slope through the origin of <span class="math inline">\(\tilde{\mathbf y}\)</span> on <span class="math inline">\(\tilde{\mathbf x}_2\)</span> is <span class="math inline">\(\tilde{\mathbf x}_2^\top\tilde{\mathbf y}/\tilde{\mathbf x}_2^\top\tilde{\mathbf x}_2\)</span>, and <span class="math inline">\(\tilde{\mathbf x}_2^\top\tilde{\mathbf y} = \tilde{\mathbf x}_2^\top\mathbf M_1\mathbf y = \tilde{\mathbf x}_2^\top\mathbf y\)</span> by the idempotence step again. (No intercept is needed in that regression: the intercept column is inside <span class="math inline">\(\mathbf X_1\)</span>, so both residuals already sum to zero.)</p>
<p>Common errors: “<span class="math inline">\(\mathbf M_1\mathbf x_2 = \mathbf 0\)</span>” (true only for the columns of <span class="math inline">\(\mathbf X_1\)</span>); asserting <span class="math inline">\(\mathbf M_1\mathbf r = \mathbf r\)</span> without saying which normal equations give it; using <span class="math inline">\(\mathbf M_1\mathbf y = \mathbf y\)</span>; dividing by <span class="math inline">\(\tilde{\mathbf x}_2^\top\tilde{\mathbf x}_2\)</span> without saying why it is not zero; writing a ratio of vectors.</p>
</div>
</div>
</div>
</section>
<section id="problems" class="level2">
<h2 class="anchored" data-anchor-id="problems">Problems</h2>
<!-- About 20 min: problems 1 and 2, pen and paper. Hints are revealed in order after a few minutes, the solution last. -->
<p><strong>Problem 1 (the constant predictor).</strong> The setting of exercise 1.</p>
<ol type="a">
<li><p>Take <span class="math inline">\(f\)</span> to be a constant <span class="math inline">\(c\)</span>. Which <span class="math inline">\(c\)</span> minimizes <span class="math inline">\(R(c)\)</span>, and what is <span class="math inline">\(R(c)\)</span> at the minimum? Express the answer in terms of <span class="math inline">\(R(f^\star)\)</span> and <span class="math inline">\(\mathrm{Var}\big(f^\star(X)\big)\)</span>.</p></li>
<li><p>Deduce that <span class="math inline">\(\mathrm{Var}(Y) = R(f^\star) + \mathrm{Var}\big(f^\star(X)\big)\)</span>, and write both terms on the right as conditional moments of <span class="math inline">\(Y\)</span> given <span class="math inline">\(X\)</span>. Which identity from ST102 is this?</p></li>
<li><p>Week 1 scored methods by squared error on held-out data. Imagine two oracle entries: one predicts <span class="math inline">\(\mathbb E Y\)</span> for everyone, the other is <span class="math inline">\(f^\star\)</span>. What is the gap between their risks? On an actual leaderboard the constant entry uses the training mean <span class="math inline">\(\bar y\)</span> and the best entry is some fitted <span class="math inline">\(\hat f\)</span>; give two reasons the observed gap need not equal that quantity. Can any method’s held-out squared error be below <span class="math inline">\(R(f^\star)\)</span> on average?</p></li>
</ol>
<div class="answer callout callout-style-default callout-note callout-titled" title="Hint 1">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li>Apply the theorem with <span class="math inline">\(f = c\)</span>, then add and subtract <span class="math inline">\(\mathbb E f^\star(X)\)</span> inside the remaining square: exercise 1’s move again, with nothing left to condition on.</li>
</ol>
</div>
</div>
</div>
<div class="answer callout callout-style-default callout-note callout-titled" title="Hint 2">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol start="2" type="a">
<li><span class="math inline">\(R(\mathbb E Y)\)</span> is a variance you know. (c) Apply the theorem to a fitted <span class="math inline">\(\hat f\)</span> conditionally on the training data.</li>
</ol>
</div>
</div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>By the theorem, <span class="math inline">\(R(c) = R(f^\star) + \mathbb E[(f^\star(X) - c)^2]\)</span>, and <span class="math inline">\(\mathbb E[(f^\star(X) - c)^2] = \mathrm{Var}(f^\star(X)) + (\mathbb E f^\star(X) - c)^2\)</span> (hint 1: the cross term is zero because <span class="math inline">\(f^\star(X) - \mathbb E f^\star(X)\)</span> has mean zero). So the minimizer is <span class="math inline">\(c^\star = \mathbb E f^\star(X) = \mathbb E Y\)</span>, by the tower property, and <span class="math inline">\(R(c^\star) = R(f^\star) + \mathrm{Var}(f^\star(X))\)</span>.</p></li>
<li><p><span class="math inline">\(R(\mathbb E Y) = \mathbb E[(Y - \mathbb E Y)^2] = \mathrm{Var}(Y)\)</span>, so <span class="math inline">\(\mathrm{Var}(Y) = R(f^\star) + \mathrm{Var}(f^\star(X))\)</span>. Conditioning on <span class="math inline">\(X\)</span> inside <span class="math inline">\(R(f^\star)\)</span> gives <span class="math inline">\(R(f^\star) = \mathbb E\big[\mathbb E[(Y - \mathbb E[Y \mid X])^2 \mid X]\big] = \mathbb E[\mathrm{Var}(Y \mid X)]\)</span>, and <span class="math inline">\(\mathrm{Var}(f^\star(X)) = \mathrm{Var}(\mathbb E[Y \mid X])\)</span>. This is the law of total variance, <span class="math inline">\(\mathrm{Var}(Y) = \mathbb E[\mathrm{Var}(Y \mid X)] + \mathrm{Var}(\mathbb E[Y \mid X])\)</span>: the optimal model theorem evaluated at the best constant.</p></li>
<li><p><span class="math inline">\(R(\mathbb E Y) - R(f^\star) = \mathrm{Var}(f^\star(X))\)</span> by (b): the part of the variance of <span class="math inline">\(Y\)</span> that is predictable from <span class="math inline">\(X\)</span> at all. Equivalently <span class="math inline">\(1 - R(f^\star)/\mathrm{Var}(Y)\)</span> is the ceiling on the population <span class="math inline">\(R^2\)</span> of every method, a property of the joint distribution of <span class="math inline">\((X, Y)\)</span> and not of any method. An observed gap differs from it for three reasons: the constant entry is <span class="math inline">\(\bar y\)</span>, not <span class="math inline">\(\mathbb E Y\)</span>, and <span class="math inline">\(R(\bar y) = \mathrm{Var}(Y) + (\bar y - \mathbb E Y)^2\)</span>, an extra term of order <span class="math inline">\(\mathrm{Var}(Y)/n\)</span> on average; the best entry is a fitted <span class="math inline">\(\hat f\)</span>, not <span class="math inline">\(f^\star\)</span>, and its risk exceeds <span class="math inline">\(R(f^\star)\)</span> by its own excess risk <span class="math inline">\(\mathbb E[(f^\star(X) - \hat f(X))^2]\)</span>, which reduces the gap, other things equal; and both scores are averages over a finite test set, which is what the error bars on week 1’s leaderboard were for. No: for a fitted <span class="math inline">\(\hat f\)</span> and a fresh pair <span class="math inline">\((X, Y)\)</span> independent of the training data, the theorem applied conditionally on the training data gives <span class="math inline">\(\mathbb E[(Y - \hat f(X))^2] = R(f^\star) + \mathbb E[(f^\star(X) - \hat f(X))^2] \ge R(f^\star)\)</span>; a score below <span class="math inline">\(R(f^\star)\)</span> is test-set noise.</p></li>
</ol>
<p>Common errors: differentiating <span class="math inline">\(\mathbb E[(Y - c)^2]\)</span> in <span class="math inline">\(c\)</span> directly (correct, but it misses that this is the theorem again); <span class="math inline">\(\mathrm{Var}(Y) = R(f^\star)\)</span>, forgetting the predictable part; in (c), “a better method could beat <span class="math inline">\(R(f^\star)\)</span>”: nothing can, on average, by the theorem.</p>
</div>
</div>
</div>
<p><strong>Problem 2 (leaving a variable out, exactly).</strong> The setting of exercise 2, but forget the truth: let <span class="math inline">\(\hat\beta_1\)</span> and <span class="math inline">\(\hat\beta_2\)</span> be the least-squares coefficients from the long regression of <span class="math inline">\(\mathbf y\)</span> on both <span class="math inline">\(\mathbf x_1\)</span> and <span class="math inline">\(\mathbf x_2\)</span>, with residual <span class="math inline">\(\mathbf r\)</span>, so that <span class="math inline">\(\mathbf y = \hat\beta_1\mathbf x_1 + \hat\beta_2\mathbf x_2 + \mathbf r\)</span>.</p>
<ol type="a">
<li><p>Show that <span class="math inline">\(\hat\beta_{\text{short}} = \hat\beta_1 + \hat\beta_2\,\hat\delta\)</span> exactly, with no expectation. Which fact about <span class="math inline">\(\mathbf r\)</span> did you use?</p></li>
<li><p>Numbers: <span class="math inline">\(\mathbf x_1 = (-1, 0, 1)\)</span>, <span class="math inline">\(\mathbf x_2 = (-2, 1, 1)\)</span>, <span class="math inline">\(\beta_1 = 1\)</span>, <span class="math inline">\(\beta_2 = 2\)</span>. Compute <span class="math inline">\(\hat\delta\)</span>, and what the short regression estimates on average.</p></li>
<li><p>Suppose <span class="math inline">\(\mathbf x_1^\top\mathbf x_2 = 0\)</span>. What happens to the coefficient on <span class="math inline">\(\mathbf x_1\)</span> when <span class="math inline">\(\mathbf x_2\)</span> is dropped? Reconcile your answer with the partialling-out theorem: what is the residual of <span class="math inline">\(\mathbf x_1\)</span> after regressing it on <span class="math inline">\(\mathbf x_2\)</span>?</p></li>
</ol>
<div class="answer callout callout-style-default callout-note callout-titled" title="Hint 1">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li>Multiply the fitted equation <span class="math inline">\(\mathbf y = \hat\beta_1\mathbf x_1 + \hat\beta_2\mathbf x_2 + \mathbf r\)</span> by <span class="math inline">\(\mathbf x_1^\top\)</span>, as in exercise 2, and look at the last term.</li>
</ol>
</div>
</div>
</div>
<div class="answer callout callout-style-default callout-note callout-titled" title="Hint 2">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li>Which fact about a least-squares residual makes that last term vanish exactly? It is the sample version of the fact that killed the cross term in exercise 1. (c) In the theorem, partial <span class="math inline">\(\mathbf x_2\)</span> out of <span class="math inline">\(\mathbf x_1\)</span>: what is left of <span class="math inline">\(\mathbf x_1\)</span> when the two are orthogonal?</li>
</ol>
</div>
</div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>Multiplying by <span class="math inline">\(\mathbf x_1^\top\)</span> and dividing by <span class="math inline">\(\mathbf x_1^\top\mathbf x_1\)</span>: <span class="math inline">\(\hat\beta_{\text{short}} = \hat\beta_1 + \hat\beta_2\hat\delta + \mathbf x_1^\top\mathbf r/\mathbf x_1^\top\mathbf x_1\)</span>, and <span class="math inline">\(\mathbf x_1^\top\mathbf r = 0\)</span> by the normal equations. The fact: <strong>a least-squares residual is orthogonal to every column it was fitted on</strong>, the sample twin of exercise 1’s population fact (the residual <span class="math inline">\(Y - f^\star(X)\)</span> is orthogonal to every function of <span class="math inline">\(X\)</span>). The same algebra as exercise 2 with the fitted coefficients in place of the truth and the residual in place of the noise, except that the last term is exactly zero rather than zero on average: the noise is not orthogonal to <span class="math inline">\(\mathbf x_1\)</span> in the sample, only mean zero given the inputs, which is why exercise 2 needs an expectation and this problem does not. Coding part 3 checks the identity on real data to every printed digit.</p></li>
<li><p>Both vectors are centered, so the formula applies as written. <span class="math inline">\(\mathbf x_1^\top\mathbf x_2 = 2 + 0 + 1 = 3\)</span> and <span class="math inline">\(\mathbf x_1^\top\mathbf x_1 = 2\)</span>, so <span class="math inline">\(\hat\delta = 1.5\)</span> and <span class="math inline">\(\mathbb E\,\hat\beta_{\text{short}} = 1 + 2 \times 1.5 = 4\)</span>: four times the coefficient it was meant to estimate.</p></li>
<li><p><span class="math inline">\(\hat\delta = 0\)</span>, so <span class="math inline">\(\hat\beta_{\text{short}} = \hat\beta_1\)</span>: dropping an orthogonal column does not move the coefficient, and by exercise 2 the short regression is then unbiased. From the theorem: partial <span class="math inline">\(\mathbf x_2\)</span> out of <span class="math inline">\(\mathbf x_1\)</span>; the residual is <span class="math inline">\(\mathbf x_1 - \mathbf x_2\,(\mathbf x_2^\top\mathbf x_1)/(\mathbf x_2^\top\mathbf x_2) = \mathbf x_1\)</span> when the two are orthogonal, so the long coefficient on <span class="math inline">\(\mathbf x_1\)</span> is <span class="math inline">\(\mathbf x_1^\top\mathbf y/\mathbf x_1^\top\mathbf x_1\)</span>, which is the short one. On the standard error: the two regressions estimate the noise variance from different residuals, and the short one’s residual still contains <span class="math inline">\(\hat\beta_2\mathbf x_2\)</span>, so the reported standard error usually grows when a relevant orthogonal column is dropped even though the coefficient does not move; the details are for the validation week.</p></li>
</ol>
<p>Common errors: raw vectors in place of centered ones; believing (a) needs an expectation (it is an identity of the data); in (c), “the coefficient is the same, so the two regressions are the same” (the residuals differ).</p>
</div>
</div>
</div>
<section id="optional-can-be-done-at-home" class="level3">
<h3 class="anchored" data-anchor-id="optional-can-be-done-at-home">Optional, can be done at home</h3>
<!-- Not in the seminar. The hat-matrix facts are checked numerically in coding part 1 and reused in the validation week. Hints are in the student file. -->
<p><strong>Problem 3 (normal equations, and centering).</strong> Simple regression, from the lecture’s “nice geometry” slide. The training error is <span class="math inline">\(\hat R_n(\alpha, \beta) = \frac1n\sum_{i=1}^n (y_i - \alpha - \beta x_i)^2\)</span>.</p>
<ol type="a">
<li><p>Compute <span class="math inline">\(\partial \hat R_n/\partial\alpha\)</span> and <span class="math inline">\(\partial \hat R_n/\partial\beta\)</span>, set both to zero, and show that the residuals <span class="math inline">\(r_i = y_i - \hat\alpha - \hat\beta x_i\)</span> satisfy <span class="math inline">\(\sum_i r_i = 0\)</span> and <span class="math inline">\(\sum_i x_i r_i = 0\)</span>. Write the same two equations as <span class="math inline">\(\mathbf X^\top \mathbf r = \mathbf 0\)</span> with <span class="math inline">\(\mathbf X = [\mathbf 1 \;\; \mathbf x]\)</span>.</p></li>
<li><p>Solve them: show <span class="math inline">\(\hat\beta = \sum_i (x_i - \bar x)(y_i - \bar y) \big/ \sum_i (x_i - \bar x)^2\)</span> and <span class="math inline">\(\hat\alpha = \bar y - \hat\beta \bar x\)</span>.</p></li>
<li><p>In the partialling-out theorem take <span class="math inline">\(\mathbf X_1 = \mathbf 1\)</span>, the column of ones, and <span class="math inline">\(\mathbf x_2 = \mathbf x\)</span>. What is <span class="math inline">\(\mathbf M_1 \mathbf x\)</span>? Conclude that the slope of <span class="math inline">\(\mathbf y\)</span> on <span class="math inline">\(\mathbf x\)</span> in a regression <em>with</em> an intercept is the slope through the origin of the centered <span class="math inline">\(\mathbf y\)</span> on the centered <span class="math inline">\(\mathbf x\)</span>, and check that this is (b).</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 1">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li>Differentiate one term of the sum first. (b) Use the first equation to eliminate <span class="math inline">\(\hat\alpha\)</span> from the second.</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 2">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol start="3" type="a">
<li><span class="math inline">\(\mathbf H_1 = \mathbf 1(\mathbf 1^\top\mathbf 1)^{-1}\mathbf 1^\top\)</span>: what is <span class="math inline">\(\mathbf 1^\top\mathbf 1\)</span>, and what does <span class="math inline">\(\mathbf H_1\)</span> do to a vector?</li>
</ol>
</div>
</div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p><span class="math inline">\(\partial \hat R_n/\partial\alpha = -\frac2n\sum_i (y_i - \alpha - \beta x_i)\)</span> and <span class="math inline">\(\partial \hat R_n/\partial\beta = -\frac2n\sum_i x_i (y_i - \alpha - \beta x_i)\)</span>. Setting both to zero at <span class="math inline">\((\hat\alpha, \hat\beta)\)</span> gives <span class="math inline">\(\sum_i r_i = 0\)</span> and <span class="math inline">\(\sum_i x_i r_i = 0\)</span>: the two rows of <span class="math inline">\(\mathbf X^\top\mathbf r = \mathbf 0\)</span>, one per column of <span class="math inline">\(\mathbf X\)</span>. Since <span class="math inline">\(\bar r = 0\)</span> and <span class="math inline">\(\sum x_i r_i = 0\)</span>, the sample correlation of <span class="math inline">\(x\)</span> and <span class="math inline">\(r\)</span> is zero: no <em>linear</em> signal is left in the residuals, which is all least squares promises.</p></li>
<li><p>The first equation gives <span class="math inline">\(\hat\alpha = \bar y - \hat\beta \bar x\)</span>. Substitute into the second: <span class="math inline">\(\sum_i x_i (y_i - \bar y - \hat\beta(x_i - \bar x)) = 0\)</span>, and because <span class="math inline">\(\sum_i (y_i - \bar y) = 0 = \sum_i (x_i - \bar x)\)</span> you may replace <span class="math inline">\(x_i\)</span> by <span class="math inline">\(x_i - \bar x\)</span> in the sum, giving <span class="math inline">\(\hat\beta = \sum_i (x_i - \bar x)(y_i - \bar y) / \sum_i (x_i - \bar x)^2\)</span>.</p></li>
<li><p><span class="math inline">\(\mathbf H_1 = \mathbf 1(\mathbf 1^\top\mathbf 1)^{-1}\mathbf 1^\top = \frac1n \mathbf 1\mathbf 1^\top\)</span>, so <span class="math inline">\(\mathbf H_1\mathbf x = \bar x\mathbf 1\)</span> and <span class="math inline">\(\mathbf M_1\mathbf x = \mathbf x - \bar x\mathbf 1\)</span>: partialling out the intercept <em>is</em> centering. The theorem gives <span class="math inline">\(\hat\beta = \tilde{\mathbf x}^\top\mathbf y/\tilde{\mathbf x}^\top\tilde{\mathbf x}\)</span> with <span class="math inline">\(\tilde{\mathbf x} = \mathbf x - \bar x\mathbf 1\)</span>, and since <span class="math inline">\(\tilde{\mathbf x}^\top \mathbf y = \tilde{\mathbf x}^\top(\mathbf y - \bar y\mathbf 1)\)</span> (the centered <span class="math inline">\(\tilde{\mathbf x}\)</span> sums to zero) this is <span class="math inline">\(\sum (x_i - \bar x)(y_i - \bar y)/\sum(x_i - \bar x)^2\)</span>, part (b). The same step is why exercise 2 and problem 2 use centered vectors whenever an intercept is fitted.</p></li>
</ol>
<p>Common errors: the chain rule’s <span class="math inline">\(-1\)</span> (harmless here); in (b), dividing by <span class="math inline">\(\sum x_i^2\)</span> instead of <span class="math inline">\(\sum (x_i - \bar x)^2\)</span>.</p>
</div>
</div>
</div>
<p><strong>Problem 4 (the hat matrix).</strong> <span class="math inline">\(\mathbf X\)</span> is <span class="math inline">\(n \times q\)</span> with full column rank (<span class="math inline">\(q = p + 1\)</span> columns, the intercept counted), <span class="math inline">\(\mathbf H = \mathbf X(\mathbf X^\top\mathbf X)^{-1}\mathbf X^\top\)</span> and <span class="math inline">\(\mathbf M = \mathbf I - \mathbf H\)</span>.</p>
<ol type="a">
<li><p>Show <span class="math inline">\(\mathbf H^2 = \mathbf H\)</span> and <span class="math inline">\(\mathbf H^\top = \mathbf H\)</span>, and compute <span class="math inline">\(\mathrm{tr}(\mathbf H)\)</span>.</p></li>
<li><p>Show <span class="math inline">\(\mathbf M^2 = \mathbf M\)</span>, <span class="math inline">\(\mathbf M^\top = \mathbf M\)</span> and <span class="math inline">\(\mathbf M \mathbf X = \mathbf 0\)</span>. In one sentence each: what is <span class="math inline">\(\mathbf H\mathbf y\)</span>, and what is <span class="math inline">\(\mathbf M\mathbf y\)</span>?</p></li>
<li><p>Use (b) to show that the residual vector <span class="math inline">\(\mathbf r = \mathbf M\mathbf y\)</span> satisfies <span class="math inline">\(\mathbf X^\top \mathbf r = \mathbf 0\)</span> (the normal equations again, from the geometry instead of the calculus). Where did full column rank get used?</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 1">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li>For the trace, <span class="math inline">\(\mathrm{tr}(\mathbf A\mathbf B) = \mathrm{tr}(\mathbf B\mathbf A)\)</span> with <span class="math inline">\(\mathbf A = \mathbf X\)</span>.</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 2">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol start="3" type="a">
<li>Write <span class="math inline">\(\mathbf X^\top\mathbf r = \mathbf X^\top\mathbf M\mathbf y\)</span> and use <span class="math inline">\(\mathbf M^\top = \mathbf M\)</span> to move <span class="math inline">\(\mathbf M\)</span> onto <span class="math inline">\(\mathbf X\)</span>.</li>
</ol>
</div>
</div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p><span class="math inline">\(\mathbf H^2 = \mathbf X(\mathbf X^\top\mathbf X)^{-1}\mathbf X^\top\mathbf X(\mathbf X^\top\mathbf X)^{-1}\mathbf X^\top = \mathbf H\)</span>, the middle <span class="math inline">\((\mathbf X^\top\mathbf X)^{-1}\mathbf X^\top\mathbf X\)</span> cancelling; <span class="math inline">\(\mathbf H^\top = \mathbf H\)</span> because <span class="math inline">\((\mathbf X^\top\mathbf X)^{-1}\)</span> is symmetric; <span class="math inline">\(\mathrm{tr}(\mathbf H) = \mathrm{tr}\big((\mathbf X^\top\mathbf X)^{-1}\mathbf X^\top\mathbf X\big) = \mathrm{tr}(\mathbf I_q) = q\)</span> by the cyclic property <span class="math inline">\(\mathrm{tr}(\mathbf A\mathbf B) = \mathrm{tr}(\mathbf B\mathbf A)\)</span>. So the hat matrix has trace <span class="math inline">\(p + 1\)</span> with the intercept counted: the number of coefficients. (The validation week turns this trace into degrees of freedom.)</p></li>
<li><p><span class="math inline">\(\mathbf M^2 = \mathbf I - 2\mathbf H + \mathbf H^2 = \mathbf I - \mathbf H = \mathbf M\)</span>; symmetric because <span class="math inline">\(\mathbf H\)</span> is; <span class="math inline">\(\mathbf M\mathbf X = \mathbf X - \mathbf X(\mathbf X^\top\mathbf X)^{-1}\mathbf X^\top\mathbf X = \mathbf X - \mathbf X = \mathbf 0\)</span>. <span class="math inline">\(\mathbf H\mathbf y\)</span> is the fitted vector <span class="math inline">\(\hat{\mathbf y}\)</span>, the point of <span class="math inline">\(\mathrm{col}(\mathbf X)\)</span> closest to <span class="math inline">\(\mathbf y\)</span>; <span class="math inline">\(\mathbf M\mathbf y\)</span> is the residual vector, what is left of <span class="math inline">\(\mathbf y\)</span> after <span class="math inline">\(\mathrm{col}(\mathbf X)\)</span> has explained what it can.</p></li>
<li><p><span class="math inline">\(\mathbf X^\top\mathbf r = \mathbf X^\top\mathbf M\mathbf y = (\mathbf M\mathbf X)^\top\mathbf y = \mathbf 0\)</span>, using <span class="math inline">\(\mathbf M^\top = \mathbf M\)</span> and <span class="math inline">\(\mathbf M\mathbf X = \mathbf 0\)</span>. Full column rank is what makes <span class="math inline">\(\mathbf X^\top\mathbf X\)</span> invertible, so that <span class="math inline">\(\mathbf H\)</span> is defined at all; without it the projection onto <span class="math inline">\(\mathrm{col}(\mathbf X)\)</span> still exists (a pseudoinverse gives it) but the coefficients are not unique, which is the <code>NA</code> that <code>lm</code> prints when one column is a copy of the others.</p></li>
</ol>
<p>Common errors: <span class="math inline">\(\mathrm{tr}(\mathbf H) = n\)</span> (confusing <span class="math inline">\(\mathbf H\)</span> with the identity); claiming <span class="math inline">\(\mathbf H = \mathbf I\)</span> because <span class="math inline">\(\mathbf H^2 = \mathbf H\)</span>.</p>
</div>
</div>
</div>
<p><strong>Problem 5 (a zero slope with a predictable outcome).</strong> Let <span class="math inline">\(X\)</span> take the values <span class="math inline">\(-1, 0, 1\)</span> with probability <span class="math inline">\(1/3\)</span> each, let <span class="math inline">\(\varepsilon\)</span> be independent of <span class="math inline">\(X\)</span> and take the values <span class="math inline">\(-1, 1\)</span> with probability <span class="math inline">\(1/2\)</span> each, and let <span class="math inline">\(Y = X^2 + \varepsilon\)</span>.</p>
<ol type="a">
<li><p>Find <span class="math inline">\(f^\star(x)\)</span> under squared loss, and its risk <span class="math inline">\(R(f^\star)\)</span>.</p></li>
<li><p>Find the best linear predictor <span class="math inline">\(a + bX\)</span>, the minimizer of <span class="math inline">\(\mathbb E[(Y - a - bX)^2]\)</span>, and its risk. Compute <span class="math inline">\(\mathrm{Cov}(X, Y)\)</span>.</p></li>
<li><p>What does the example say about using correlation to decide whether <span class="math inline">\(X\)</span> predicts <span class="math inline">\(Y\)</span>? Which result from the lecture gives the excess risk of the best line, and what is it here?</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 1">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><span class="math inline">\(\mathbb E[Y \mid X = x]\)</span> is <span class="math inline">\(x^2\)</span> plus the mean of the noise.</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 2">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol start="2" type="a">
<li>The best line’s slope is <span class="math inline">\(\mathrm{Cov}(X, Y)/\mathrm{Var}(X)\)</span>; compute <span class="math inline">\(\mathbb E X^3\)</span>. Its risk is then the variance of something.</li>
</ol>
</div>
</div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p><span class="math inline">\(f^\star(x) = \mathbb E[Y \mid X = x] = x^2\)</span>, because <span class="math inline">\(\varepsilon\)</span> is independent of <span class="math inline">\(X\)</span> with mean zero; <span class="math inline">\(R(f^\star) = \mathbb E\,\varepsilon^2 = 1\)</span>.</p></li>
<li><p><span class="math inline">\(\mathbb E X = 0\)</span> and <span class="math inline">\(\mathbb E X^3 = 0\)</span>, so <span class="math inline">\(\mathrm{Cov}(X, Y) = \mathrm{Cov}(X, X^2) = \mathbb E X^3 - \mathbb E X\,\mathbb E X^2 = 0\)</span>: the slope is <span class="math inline">\(b = 0\)</span> and the intercept is <span class="math inline">\(a = \mathbb E Y = \mathbb E X^2 = 2/3\)</span>. Its risk is <span class="math inline">\(\mathbb E[(Y - 2/3)^2] = \mathrm{Var}(Y) = \mathrm{Var}(X^2) + \mathrm{Var}(\varepsilon) = (\mathbb E X^4 - (\mathbb E X^2)^2) + 1 = (2/3 - 4/9) + 1 = 11/9\)</span>.</p></li>
<li><p>Zero correlation and a zero slope, yet <span class="math inline">\(Y\)</span> is predictable from <span class="math inline">\(X\)</span> up to the noise: correlation detects linear signal only. The optimal model theorem gives the excess risk of any predictor as <span class="math inline">\(\mathbb E[(f^\star(X) - f(X))^2]\)</span>; for the best line that is <span class="math inline">\(\mathbb E[(X^2 - 2/3)^2] = \mathrm{Var}(X^2) = 2/9\)</span>, which is <span class="math inline">\(11/9 - 1\)</span>. The same lesson as coding part 4’s <code>x2</code>, in a case small enough to do by hand.</p></li>
</ol>
<p>Common errors: concluding from <span class="math inline">\(\mathrm{Cov}(X, Y) = 0\)</span> that <span class="math inline">\(X\)</span> carries no information about <span class="math inline">\(Y\)</span>; computing <span class="math inline">\(\mathrm{Var}(Y)\)</span> as <span class="math inline">\(\mathrm{Var}(\varepsilon)\)</span> alone.</p>
</div>
</div>
</div>
<p><strong>Problem 6 (why collinearity makes a coefficient uncertain).</strong> Fixed design: <span class="math inline">\(\mathbf y = \mathbf X_1\boldsymbol\beta_1 + \mathbf x_2\beta_2 + \boldsymbol\varepsilon\)</span> with <span class="math inline">\(\mathbb E\,\boldsymbol\varepsilon = \mathbf 0\)</span> and <span class="math inline">\(\mathrm{Cov}(\boldsymbol\varepsilon) = \sigma^2\mathbf I\)</span>, full column rank, and <span class="math inline">\(\tilde{\mathbf x}_2 = \mathbf M_1\mathbf x_2\)</span> as in the lecture.</p>
<ol type="a">
<li><p>Use the partialling-out theorem to show that <span class="math inline">\(\hat\beta_2 = \beta_2 + \tilde{\mathbf x}_2^\top\boldsymbol\varepsilon / \tilde{\mathbf x}_2^\top\tilde{\mathbf x}_2\)</span>. Which two facts about <span class="math inline">\(\mathbf M_1\)</span> do you need?</p></li>
<li><p>Find <span class="math inline">\(\mathbb E\,\hat\beta_2\)</span> and <span class="math inline">\(\mathrm{Var}(\hat\beta_2)\)</span>.</p></li>
<li><p>What happens as <span class="math inline">\(\mathbf x_2\)</span> becomes almost a linear combination of the columns of <span class="math inline">\(\mathbf X_1\)</span>? Compare two designs with <span class="math inline">\(\tilde{\mathbf x}_2^\top\tilde{\mathbf x}_2 = 100\)</span> and <span class="math inline">\(\tilde{\mathbf x}_2^\top\tilde{\mathbf x}_2 = 4\)</span>, with the same <span class="math inline">\(\sigma^2\)</span>.</p></li>
</ol>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 1">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-29-contents" aria-controls="callout-29" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 1
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-29" class="callout-29-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li>The theorem gives <span class="math inline">\(\hat\beta_2 = \tilde{\mathbf x}_2^\top\mathbf y/\tilde{\mathbf x}_2^\top\tilde{\mathbf x}_2\)</span>; substitute the model for <span class="math inline">\(\mathbf y\)</span>.</li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Hint 2">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-30-contents" aria-controls="callout-30" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Hint 2
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-30" class="callout-30-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li>You need <span class="math inline">\(\tilde{\mathbf x}_2^\top\mathbf X_1 = \mathbf 0\)</span> and <span class="math inline">\(\tilde{\mathbf x}_2^\top\mathbf x_2 = \tilde{\mathbf x}_2^\top\tilde{\mathbf x}_2\)</span>: which property of <span class="math inline">\(\mathbf M_1\)</span> gives each? (b) For the variance of a ratio with a fixed denominator, square the denominator.</li>
</ol>
</div>
</div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-31-contents" aria-controls="callout-31" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-31" class="callout-31-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="a">
<li><p>By the theorem, <span class="math inline">\(\hat\beta_2 = \tilde{\mathbf x}_2^\top\mathbf y / \tilde{\mathbf x}_2^\top\tilde{\mathbf x}_2\)</span>. Substitute the model for <span class="math inline">\(\mathbf y\)</span>: <span class="math inline">\(\tilde{\mathbf x}_2^\top\mathbf X_1 = \mathbf x_2^\top\mathbf M_1\mathbf X_1 = \mathbf 0\)</span> (<span class="math inline">\(\mathbf M_1\)</span> is symmetric and <span class="math inline">\(\mathbf M_1\mathbf X_1 = \mathbf 0\)</span>), and <span class="math inline">\(\tilde{\mathbf x}_2^\top\mathbf x_2 = \mathbf x_2^\top\mathbf M_1\mathbf x_2 = \mathbf x_2^\top\mathbf M_1\mathbf M_1\mathbf x_2 = \tilde{\mathbf x}_2^\top\tilde{\mathbf x}_2\)</span> (<span class="math inline">\(\mathbf M_1\)</span> is idempotent). So <span class="math inline">\(\hat\beta_2 = \beta_2 + \tilde{\mathbf x}_2^\top\boldsymbol\varepsilon / \tilde{\mathbf x}_2^\top\tilde{\mathbf x}_2\)</span>: the fitted coefficient is the true one plus the noise projected onto <span class="math inline">\(\tilde{\mathbf x}_2\)</span>.</p></li>
<li><p><span class="math inline">\(\mathbb E\,\hat\beta_2 = \beta_2\)</span>, and <span class="math inline">\(\mathrm{Var}(\hat\beta_2) = \tilde{\mathbf x}_2^\top(\sigma^2\mathbf I)\tilde{\mathbf x}_2 / (\tilde{\mathbf x}_2^\top\tilde{\mathbf x}_2)^2 = \sigma^2 / \tilde{\mathbf x}_2^\top\tilde{\mathbf x}_2\)</span>.</p></li>
<li><p>The denominator is the squared length of what is left of <span class="math inline">\(\mathbf x_2\)</span> after <span class="math inline">\(\mathbf X_1\)</span> has explained what it can. As <span class="math inline">\(\mathbf x_2\)</span> approaches <span class="math inline">\(\mathrm{col}(\mathbf X_1)\)</span> that length goes to zero and the variance blows up; at zero the coefficient is not identified, which is the <code>NA</code> from the lecture. With <span class="math inline">\(100\)</span> against <span class="math inline">\(4\)</span> the variance ratio is <span class="math inline">\(25\)</span>: a standard deviation five times larger in the second design. Collinearity does not bias the coefficient; it makes it uncertain, and the picture in the lecture says why: a short <span class="math inline">\(\tilde{\mathbf x}_2\)</span> is a short baseline for a slope.</p></li>
</ol>
<p>Common errors: writing <span class="math inline">\(\mathrm{Var}(\hat\beta_2) = \sigma^2/\mathbf x_2^\top\mathbf x_2\)</span> (the raw column instead of the residual), which is the variance in the regression on <span class="math inline">\(\mathbf x_2\)</span> alone; forgetting the square in the denominator when taking the variance of the ratio.</p>
</div>
</div>
</div>
</section>
</section>
<section id="coding" class="level2">
<h2 class="anchored" data-anchor-id="coding">Coding</h2>
<!-- About 35 min: part 1 5, part 2 10, part 3 12, part 4 8. Skeleton lines in comments are scaffolds: the statistical operation is what you write. Everything headed "Optional, can be done at home" is outside the seminar. -->
<section id="matrices-and-vectors-in-r" class="level3">
<h3 class="anchored" data-anchor-id="matrices-and-vectors-in-r">1. Matrices and vectors in R</h3>
<!-- 5 min: step 1. The pieces and step 2 are optional. -->
<p>The lecture’s formula <span class="math inline">\(\hat\beta = (\mathbf X^\top\mathbf X)^{-1}\mathbf X^\top\mathbf y\)</span> is a few lines of R.</p>
<section id="optional-can-be-done-at-home-the-pieces" class="level4">
<h4 class="anchored" data-anchor-id="optional-can-be-done-at-home-the-pieces">Optional, can be done at home: the pieces</h4>
<p>Skip to step 1 if <code>%*%</code>, <code>t()</code> and <code>solve()</code> are familiar.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># byrow = FALSE default</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>, <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">ncol =</span> <span class="dv">3</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>x</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">3</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>beta</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 1 1</code></pre>
</div>
</div>
<p>Multiplication is <code>%*%</code> (yes, really). Beware “Error: non-conformable arguments”; always check dimensions. If the dimension of one object divides the dimension of another, R may “conveniently” (unintuitively) repeat the smaller one.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(x)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3 3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(beta) <span class="co"># frustrating</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>NULL</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>x <span class="sc">%*%</span> beta</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]
[1,]   12
[2,]   15
[3,]   18</code></pre>
</div>
</div>
<p>Transpose and symmetry: even if a matrix <span class="math inline">\(\mathbf A\)</span> is not square, both <span class="math inline">\(\mathbf A^\top\mathbf A\)</span> and <span class="math inline">\(\mathbf A\mathbf A^\top\)</span> are square and symmetric (often one is invertible).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>A <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">4</span>), <span class="dv">0</span>, <span class="dv">0</span>), <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">byrow =</span> <span class="cn">FALSE</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>A</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]    1    1
[2,]    1    0
[3,]    1    0</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(A) <span class="sc">%*%</span> A</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1] [,2]
[1,]    3    1
[2,]    1    1</code></pre>
</div>
</div>
<p>Pseudoinversion: <code>ginv()</code> in the <code>MASS</code> library (installed with R) computes <span class="math inline">\(\mathbf A^\dagger = (\mathbf A^\top\mathbf A)^{-1}\mathbf A^\top\)</span> when that exists, so <span class="math inline">\(\mathbf A^\dagger\mathbf A = \mathbf I\)</span>; it is a left inverse here, not a right one.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>Ainv <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">ginv</span>(A)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>Ainv <span class="sc">%*%</span> A   <span class="co"># the 2 x 2 identity matrix</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]         [,2]
[1,]    1 1.578934e-16
[2,]    0 1.000000e+00</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>A <span class="sc">%*%</span> Ainv   <span class="co"># not a right inverse</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             [,1]         [,2]         [,3]
[1,] 1.000000e+00 5.551115e-17 5.551115e-17
[2,] 1.578934e-16 5.000000e-01 5.000000e-01
[3,] 1.578934e-16 5.000000e-01 5.000000e-01</code></pre>
</div>
</div>
</section>
<section id="the-formula" class="level4">
<h4 class="anchored" data-anchor-id="the-formula">The formula</h4>
<p><strong>Step 1.</strong> Take the 2007 countries, build the design matrix for <code>lifeExp ~ lgdp + lpop</code> with <code>model.matrix</code> (it adds the column of ones), and compute <span class="math inline">\(\hat\beta\)</span> from the formula. Compare with <code>lm</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>gm <span class="ot">&lt;-</span> gapminder <span class="sc">|&gt;</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2007</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">lgdp =</span> <span class="fu">log10</span>(gdpPercap), <span class="at">lpop =</span> <span class="fu">log10</span>(pop))</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(lifeExp <span class="sc">~</span> lgdp <span class="sc">+</span> lpop, <span class="at">data =</span> gm)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> gm<span class="sc">$</span>lifeExp</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(X, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)     lgdp     lpop
1           1 2.988818 7.503653
2           1 3.773569 6.556366
3           1 3.794025 7.522877</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># beta_hat &lt;- solve(____ %*% ____) %*% ____ %*% ____</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># cbind(formula = beta_hat, lm = coef(lm(lifeExp ~ lgdp + lpop, data = gm)))</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>...</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-32-contents" aria-controls="callout-32" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-32" class="callout-32-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>beta_hat <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X) <span class="sc">%*%</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> y</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(<span class="at">formula =</span> beta_hat, <span class="at">lm =</span> <span class="fu">coef</span>(<span class="fu">lm</span>(lifeExp <span class="sc">~</span> lgdp <span class="sc">+</span> lpop, <span class="at">data =</span> gm)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                             lm
(Intercept) -8.616113 -8.616113
lgdp        16.681183 16.681183
lpop         1.868279  1.868279</code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Checkpoint (run it; if it stops, check the order of the factors in the formula):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">isTRUE</span>(<span class="fu">all.equal</span>(<span class="fu">as.numeric</span>(beta_hat),</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                           <span class="fu">as.numeric</span>(<span class="fu">coef</span>(<span class="fu">lm</span>(lifeExp <span class="sc">~</span> lgdp <span class="sc">+</span> lpop, <span class="at">data =</span> gm))))))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="optional-can-be-done-at-home-the-hat-matrix" class="level4">
<h4 class="anchored" data-anchor-id="optional-can-be-done-at-home-the-hat-matrix">Optional, can be done at home: the hat matrix</h4>
<p><strong>Step 2.</strong> Build the hat matrix <span class="math inline">\(\mathbf H = \mathbf X(\mathbf X^\top\mathbf X)^{-1}\mathbf X^\top\)</span> and check two of its properties numerically: its trace, and that <span class="math inline">\(\mathbf H\mathbf y\)</span> is <code>fitted(lm(...))</code>. (Optional problem 4 proves them.)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># H &lt;- ____</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="co"># c(trace = sum(diag(H)), n = nrow(X), q = ncol(X))</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co"># all.equal(as.numeric(H %*% y), as.numeric(fitted(lm(lifeExp ~ lgdp + lpop, data = gm))))</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>...</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-33-contents" aria-controls="callout-33" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-33" class="callout-33-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>H <span class="ot">&lt;-</span> X <span class="sc">%*%</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X) <span class="sc">%*%</span> <span class="fu">t</span>(X)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">trace =</span> <span class="fu">sum</span>(<span class="fu">diag</span>(H)), <span class="at">n =</span> <span class="fu">nrow</span>(X), <span class="at">q =</span> <span class="fu">ncol</span>(X))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>trace     n     q 
    3   142     3 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(<span class="fu">as.numeric</span>(H <span class="sc">%*%</span> y), <span class="fu">as.numeric</span>(<span class="fu">fitted</span>(<span class="fu">lm</span>(lifeExp <span class="sc">~</span> lgdp <span class="sc">+</span> lpop, <span class="at">data =</span> gm))))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
</div>
</div>
</div>
<p><strong>Question 1.</strong> The trace came out as a small integer. Which one, and why?</p>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-34-contents" aria-controls="callout-34" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-34" class="callout-34-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(3 = q\)</span>, the number of columns of <span class="math inline">\(\mathbf X\)</span> (intercept, <code>lgdp</code>, <code>lpop</code>): <span class="math inline">\(\mathrm{tr}(\mathbf H) = \mathrm{tr}\big((\mathbf X^\top\mathbf X)^{-1}\mathbf X^\top\mathbf X\big) = \mathrm{tr}(\mathbf I_q)\)</span> by the cyclic property of the trace. It is the number of coefficients, not <span class="math inline">\(n\)</span> (optional problem 4(a)). Building <code>H</code> with <code>MASS::ginv(X)</code> instead of the explicit inverse gives the same matrix.</p>
</div>
</div>
</div>
</section>
</section>
<section id="regression-on-real-data" class="level3">
<h3 class="anchored" data-anchor-id="regression-on-real-data">2. Regression on real data</h3>
<!-- 10 min: steps 1 and 3 and question 2. Step 2 and the block at the end are optional. -->
<p>In this part you are encouraged to use a dataset that you found interesting. Your dataset should have a numeric outcome variable and multiple predictor variables, and at least one of the predictors should also be numeric. Your dataset should not have any special structure that would clearly violate independence assumptions, e.g.&nbsp;observations with possible spatial or temporal correlation (the <code>gapminder</code> data above uses one year for this reason, so the same country is not repeated).</p>
<p>Note: we also cannot deal with missing values right now so you may use <code>drop_na()</code>. The default below is the penguins.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load dataset and pre-process if necessary</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">|&gt;</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>() <span class="ot">-&gt;</span> my_data <span class="co"># bad syntax, but fun!</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Step 1.</strong> Choose one predictor variable and fit a simple linear model. Then use each of these functions on the model object and try to understand the output: <code>summary</code>, <code>predict</code>, <code>residuals</code>, <code>coef</code>, <code>confint</code>, <code>plot</code>.</p>
<p>Many of these are shortcut functions that can be used on many different types of objects, e.g.&nbsp;models fit by other methods. To learn more about a function <code>f</code> type <code>?f</code> in the console, and to see how it works on linear model objects type <code>?f.lm</code>, e.g.&nbsp;<code>?plot.lm</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>model_simple <span class="ot">&lt;-</span> <span class="fu">lm</span>(body_mass_g <span class="sc">~</span> bill_length_mm, <span class="at">data =</span> my_data)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_simple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = body_mass_g ~ bill_length_mm, data = my_data)

Residuals:
     Min       1Q   Median       3Q      Max 
-1759.38  -468.82    27.79   464.20  1641.00 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     388.845    289.817   1.342    0.181    
bill_length_mm   86.792      6.538  13.276   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 651.4 on 331 degrees of freedom
Multiple R-squared:  0.3475,    Adjusted R-squared:  0.3455 
F-statistic: 176.2 on 1 and 331 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># predict(model_simple) ; residuals(model_simple) ; coef(model_simple) ; confint(model_simple)</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>...</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-35-contents" aria-controls="callout-35" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-35" class="callout-35-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(model_simple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   (Intercept) bill_length_mm 
     388.84516       86.79176 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(model_simple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    2.5 %    97.5 %
(Intercept)    -181.27072 958.96104
bill_length_mm   73.93115  99.65237</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">predict</span>(model_simple))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6 
3782.403 3817.120 3886.553 3574.103 3799.761 3765.045 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">residuals</span>(model_simple))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1          2          3          4          5          6 
 -32.40296  -17.11966 -636.55307 -124.10274 -149.76131 -140.04461 </code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_simple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notebook2_complete_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" style="width:48.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notebook2_complete_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" style="width:48.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notebook2_complete_files/figure-html/unnamed-chunk-15-3.png" class="img-fluid figure-img" style="width:48.0%"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notebook2_complete_files/figure-html/unnamed-chunk-15-4.png" class="img-fluid figure-img" style="width:48.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Question 2.</strong> How do we interpret diagnostic plots?</p>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-36-contents" aria-controls="callout-36" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-36" class="callout-36-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Generally looking for patterns in residuals, normality of their distribution (diagonal line in QQ plot), constant variance (homoscedasticity), and influential points (high-leverage outliers). Two cautions from the lecture: a correctly specified conditional mean gives <span class="math inline">\(\mathbb E[\text{residual} \mid X] \approx 0\)</span>, but says nothing about the spread, so a fan shape is a separate matter (constant variance is its own assumption); and a pattern in a finite noisy sample is evidence that the class of functions may be missing something, not a proof that it is.</p>
</div>
</div>
</div>
<p><strong>Step 2 (optional, can be done at home).</strong> Create a scatterplot showing your simple linear model (just like last week: <code>geom_point</code>, then <code>geom_smooth(method = "lm")</code>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># my_data |&gt; ggplot(aes(x = ____, y = ____)) + ____ + ____</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>...</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-37-contents" aria-controls="callout-37" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-37" class="callout-37-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>my_data <span class="sc">|&gt;</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> bill_length_mm, <span class="at">y =</span> body_mass_g)) <span class="sc">+</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notebook2_complete_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p><strong>Step 3.</strong> Multiple linear regression: repeat with a model using more than one predictor, and notice what’s different about the output. Then use <code>tidy</code> and <code>glance</code> from the <code>broom</code> package and compare with <code>summary</code> (see <code>?tidy.lm</code>; piping <code>tidy()</code> into <code>knitr::kable()</code> formats it nicely), and draw the coefficients with their intervals using <code>ggcoef</code> from <code>GGally</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>model_multiple <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  body_mass_g <span class="sc">~</span> bill_length_mm <span class="sc">+</span> bill_depth_mm <span class="sc">+</span> sex,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> my_data)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="co"># tidy(model_multiple, conf.int = TRUE) |&gt; knitr::kable(digits = 2)</span></span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="co"># glance(model_multiple) |&gt; knitr::kable(digits = 3)</span></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="co"># ggcoef(____)</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>...</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-38-contents" aria-controls="callout-38" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-38" class="callout-38-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>model_multiple <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  body_mass_g <span class="sc">~</span> bill_length_mm <span class="sc">+</span> bill_depth_mm <span class="sc">+</span> sex,</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> my_data)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_multiple, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">6551.44</td>
<td style="text-align: right;">394.41</td>
<td style="text-align: right;">16.61</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">5775.56</td>
<td style="text-align: right;">7327.32</td>
</tr>
<tr class="even">
<td style="text-align: left;">bill_length_mm</td>
<td style="text-align: right;">36.52</td>
<td style="text-align: right;">5.30</td>
<td style="text-align: right;">6.89</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">26.09</td>
<td style="text-align: right;">46.95</td>
</tr>
<tr class="odd">
<td style="text-align: left;">bill_depth_mm</td>
<td style="text-align: right;">-257.31</td>
<td style="text-align: right;">14.89</td>
<td style="text-align: right;">-17.28</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-286.61</td>
<td style="text-align: right;">-228.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexmale</td>
<td style="text-align: right;">923.31</td>
<td style="text-align: right;">60.72</td>
<td style="text-align: right;">15.21</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">803.85</td>
<td style="text-align: right;">1042.76</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glance</span>(model_multiple) <span class="sc">|&gt;</span> knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 2%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">deviance</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.687</td>
<td style="text-align: right;">0.684</td>
<td style="text-align: right;">452.362</td>
<td style="text-align: right;">240.98</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">-2506.617</td>
<td style="text-align: right;">5023.234</td>
<td style="text-align: right;">5042.275</td>
<td style="text-align: right;">67323723</td>
<td style="text-align: right;">329</td>
<td style="text-align: right;">333</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggcoef</span>(model_multiple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notebook2_complete_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<section id="optional-can-be-done-at-home-1" class="level4">
<h4 class="anchored" data-anchor-id="optional-can-be-done-at-home-1">Optional, can be done at home</h4>
<!-- Not in the seminar. -->
<p><code>GGally</code> also has <code>ggnostic</code>, a grid of diagnostic plots for a multiple model, one column per predictor.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ggnostic(____)</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>...</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-39-contents" aria-controls="callout-39" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-39" class="callout-39-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggnostic</span>(model_multiple)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notebook2_complete_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p>There is also a function <code>ggpairs</code> useful for exploratory data analysis, but beware that it can be slow because it computes many pairwise plots. You may not want to rerun that code many times. There is an option <code>cache: true</code> that saves the result after running it once and then refuses to run it again unless you change the code chunk. You can also leave out variables you don’t want to include using <code>select(-var1, -var2, ...)</code> or choose only some to include with <code>select(var1, var2, ...)</code>. Also see useful helper functions like <code>?tidyselect::starts_with</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># my_data |&gt;</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   select(-year, -island) |&gt;</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   ggpairs(progress = FALSE)</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>...</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-40-contents" aria-controls="callout-40" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-40" class="callout-40-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>my_data <span class="sc">|&gt;</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">"_"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggpairs</span>(<span class="at">progress =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notebook2_complete_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p><strong>Step 4.</strong> Pick at least one numeric predictor and include a non-linear transformation, e.g.&nbsp;a polynomial <code>y ~ poly(x, d)</code> or an interaction <code>y ~ x1 * x2</code>. Use <code>glance</code>, <code>tidy</code> and <code>plot</code> again on this model and note any differences.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># model_transformed &lt;- lm(____ ~ poly(____, 2) + ____, data = my_data)</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="co"># glance(model_transformed)$r.squared</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>...</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-41-contents" aria-controls="callout-41" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-41" class="callout-41-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>model_transformed <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  body_mass_g <span class="sc">~</span> <span class="fu">poly</span>(bill_length_mm, <span class="dv">2</span>) <span class="sc">+</span> bill_depth_mm <span class="sc">+</span> sex,</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> my_data)</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">linear =</span> <span class="fu">glance</span>(model_multiple)<span class="sc">$</span>r.squared,</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">quadratic =</span> <span class="fu">glance</span>(model_transformed)<span class="sc">$</span>r.squared)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   linear quadratic 
0.6872441 0.6872540 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p><strong>Question 3.</strong> The pair plots from e.g.&nbsp;<code>ggnostic</code> or <code>ggpairs</code> show many 2-dimensional projections of the data, but there is no guarantee that these projections together help us understand higher dimensional relationships. What does this mean for diagnostic plots when our regression model is high dimensional (e.g.&nbsp;<span class="math inline">\(p &gt; 3\)</span> predictors)?</p>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-42-contents" aria-controls="callout-42" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-42" class="callout-42-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It is possible there is some higher dimensional pattern in the residuals that the pairs plot does not reveal to us: the model would have failed to capture some (non-linear) signal and our diagnostic method would fail to reveal that flaw. Part 4’s required example is the opposite case, a pattern in one input that its residual plot does show; the first challenge at the end of part 4 (an interaction) builds the case that one-input plots miss.</p>
</div>
</div>
</div>
</section>
</section>
<section id="partialling-out-and-the-omitted-variable" class="level3">
<h3 class="anchored" data-anchor-id="partialling-out-and-the-omitted-variable">3. Partialling out, and the omitted variable</h3>
<!-- 12 min -->
<p>Back to the 2007 countries: life expectancy on log GDP per capita, log population and continent.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>long <span class="ot">&lt;-</span> <span class="fu">lm</span>(lifeExp <span class="sc">~</span> lgdp <span class="sc">+</span> lpop <span class="sc">+</span> continent, <span class="at">data =</span> gm)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(long) <span class="sc">|&gt;</span> knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">19.42</td>
<td style="text-align: right;">7.46</td>
<td style="text-align: right;">2.60</td>
<td style="text-align: right;">0.01</td>
</tr>
<tr class="even">
<td style="text-align: left;">lgdp</td>
<td style="text-align: right;">10.69</td>
<td style="text-align: right;">1.24</td>
<td style="text-align: right;">8.63</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">lpop</td>
<td style="text-align: right;">0.09</td>
<td style="text-align: right;">0.81</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.91</td>
</tr>
<tr class="even">
<td style="text-align: left;">continentAmericas</td>
<td style="text-align: right;">11.66</td>
<td style="text-align: right;">1.69</td>
<td style="text-align: right;">6.89</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">continentAsia</td>
<td style="text-align: right;">10.05</td>
<td style="text-align: right;">1.58</td>
<td style="text-align: right;">6.37</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">continentEurope</td>
<td style="text-align: right;">11.23</td>
<td style="text-align: right;">1.93</td>
<td style="text-align: right;">5.83</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">continentOceania</td>
<td style="text-align: right;">12.89</td>
<td style="text-align: right;">4.55</td>
<td style="text-align: right;">2.83</td>
<td style="text-align: right;">0.01</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Step 1.</strong> The partialling-out theorem says the coefficient on <code>lgdp</code> is the slope of <code>lifeExp</code> on the part of <code>lgdp</code> that the other columns cannot explain. Check it: regress <code>lgdp</code> on the other predictors (intercept included), keep the residual, and regress <code>lifeExp</code> on that residual. The two numbers should agree to every printed digit.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># lgdp_tilde &lt;- resid(lm(____ ~ ____, data = gm))</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="co"># c(full = coef(long)[["lgdp"]],</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   y_on_residual = coef(lm(gm$lifeExp ~ lgdp_tilde))[[2]])</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>...</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-43-contents" aria-controls="callout-43" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-43" class="callout-43-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>lgdp_tilde <span class="ot">&lt;-</span> <span class="fu">resid</span>(<span class="fu">lm</span>(lgdp <span class="sc">~</span> lpop <span class="sc">+</span> continent, <span class="at">data =</span> gm))</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">full =</span> <span class="fu">coef</span>(long)[[<span class="st">"lgdp"</span>]],</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y_on_residual =</span> <span class="fu">coef</span>(<span class="fu">lm</span>(gm<span class="sc">$</span>lifeExp <span class="sc">~</span> lgdp_tilde))[[<span class="dv">2</span>]])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         full y_on_residual 
     10.68756      10.68756 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p>Checkpoint:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="fu">isTRUE</span>(<span class="fu">all.equal</span>(<span class="fu">coef</span>(long)[[<span class="st">"lgdp"</span>]], <span class="fu">coef</span>(<span class="fu">lm</span>(gm<span class="sc">$</span>lifeExp <span class="sc">~</span> lgdp_tilde))[[<span class="dv">2</span>]])))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Question 4.</strong> In one sentence, what is the coefficient on <code>lgdp</code> in <code>long</code> the slope of? Your neighbor regressed the <em>residual</em> of <code>lifeExp</code> (on <code>lpop</code> and <code>continent</code>) on <code>lgdp_tilde</code> and got the same number. Why is that not a coincidence?</p>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-44-contents" aria-controls="callout-44" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-44" class="callout-44-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The slope of <code>lifeExp</code> on the part of <code>lgdp</code> not linearly explained by <code>lpop</code>, the continent indicators and the intercept. Residual on residual gives the same slope because <span class="math inline">\(\tilde{\mathbf x}_2^\top \mathbf M_1 \mathbf y = \tilde{\mathbf x}_2^\top \mathbf y\)</span>: <span class="math inline">\(\mathbf M_1\)</span> is symmetric and idempotent, so it can be moved onto <span class="math inline">\(\tilde{\mathbf x}_2\)</span>, where it changes nothing (lines 5 to 6 of the lecture’s proof). If the numbers disagree, the residual came from the wrong regression (<code>lifeExp</code> instead of <code>lgdp</code> on the left), the two fits used different rows, or a column was left out of the auxiliary regression. Dropping the explicit intercept with <code>- 1</code> does not change the answer here: R then codes every continent with its own indicator, and together they span the constant column.</p>
</div>
</div>
</div>
<p><strong>Step 2.</strong> Now leave <code>lpop</code> out. Fit the short regression <code>lifeExp ~ lgdp + continent</code>, and the auxiliary regression of the omitted variable on what was kept, <code>lpop ~ lgdp + continent</code>. Check problem 2(a): the short coefficient on <code>lgdp</code> equals the long one plus the long coefficient on <code>lpop</code> times the auxiliary slope, exactly.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># short &lt;- lm(____, data = gm)</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="co"># aux &lt;- lm(____, data = gm)</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a><span class="co"># c(short = coef(short)[["lgdp"]],</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   long_plus_correction = coef(long)[["lgdp"]] + coef(long)[["lpop"]] * coef(aux)[["lgdp"]])</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>...</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-45-contents" aria-controls="callout-45" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-45" class="callout-45-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>short <span class="ot">&lt;-</span> <span class="fu">lm</span>(lifeExp <span class="sc">~</span> lgdp <span class="sc">+</span> continent, <span class="at">data =</span> gm)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>aux <span class="ot">&lt;-</span> <span class="fu">lm</span>(lpop <span class="sc">~</span> lgdp <span class="sc">+</span> continent, <span class="at">data =</span> gm)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a><span class="fu">c</span>(<span class="at">short =</span> <span class="fu">coef</span>(short)[[<span class="st">"lgdp"</span>]],</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">long_plus_correction =</span> <span class="fu">coef</span>(long)[[<span class="st">"lgdp"</span>]] <span class="sc">+</span> <span class="fu">coef</span>(long)[[<span class="st">"lpop"</span>]] <span class="sc">*</span> <span class="fu">coef</span>(aux)[[<span class="st">"lgdp"</span>]])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               short long_plus_correction 
            10.66275             10.66275 </code></pre>
</div>
</div>
</div>
</div>
</div>
<p><strong>Question 5.</strong> Did leaving out <code>lpop</code> move the coefficient on <code>lgdp</code> by much, and in which direction? Exercise 2 names two things the size of the move depends on; which of them is small here? Is the short coefficient “wrong”?</p>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-46-contents" aria-controls="callout-46" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-46" class="callout-46-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>On these data the move is tiny, about <span class="math inline">\(0.025\)</span> years per unit of <span class="math inline">\(\log_{10}\)</span> GDP, and downward: 10.69 in the long regression, 10.66 in the short one. The long coefficient on <code>lpop</code> is itself near zero (<span class="math inline">\(0.09\)</span>), so <span class="math inline">\(\hat\beta_{\text{lpop}} \times \hat\delta = 0.09 \times (-0.27)\)</span> is small even though the auxiliary slope <span class="math inline">\(\hat\delta = -0.27\)</span> is not. The size is the product of the two: how much the omitted variable matters <em>and</em> how correlated it is with what was kept, given the other columns. “Wrong” is the wrong word: the short and long coefficients are slopes on different residuals and answer different questions; which one you want depends on what you are holding fixed on purpose, and next week is about deciding that. (Problem 2(a) was stated for two predictors; with the continent indicators in both regressions the same algebra goes through, because the normal equations make the long residual orthogonal to every kept column, so the identity holds exactly as checked here.)</p>
</div>
</div>
</div>
</section>
<section id="regression-models-with-simulated-data" class="level3">
<h3 class="anchored" data-anchor-id="regression-models-with-simulated-data">4. Regression models with simulated data</h3>
<!-- 8 min: the simulation code is written; the work is step 1 and question 6. The block at the end is optional. -->
<p>Now we want to simulate data in various ways, fit regression models to the data while pretending we don’t know how it was generated, and then see how those models perform. We want to understand the limitations of regression models. <em>If something was wrong with the model, would we be able to tell?</em></p>
<p>Choose a functional form for the true outcome data generation process:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="cf">function</span>(x1, x2, x3) x1 <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span>x2 <span class="sc">-</span> x2<span class="sc">^</span><span class="dv">2</span> <span class="co"># change this</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Generate several predictor variables, an error term, and an outcome:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>simulate_data <span class="ot">&lt;-</span> <span class="cf">function</span>(n) {</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>  x1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">3</span>, <span class="at">sd =</span> <span class="dv">3</span>) <span class="co"># change</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>  x2 <span class="ot">&lt;-</span> <span class="fu">runif</span>(n, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">2</span>) <span class="co"># change</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>  x3 <span class="ot">&lt;-</span> <span class="fu">rexp</span>(n, <span class="at">rate =</span> <span class="dv">2</span>) <span class="co"># change</span></span>
<span id="cb66-5"><a href="#cb66-5" aria-hidden="true" tabindex="-1"></a>  errors <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> <span class="dv">1</span>) <span class="co"># change</span></span>
<span id="cb66-6"><a href="#cb66-6" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">f</span>(x1, x2, x3) <span class="sc">+</span> errors</span>
<span id="cb66-7"><a href="#cb66-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">y =</span> y,</span>
<span id="cb66-8"><a href="#cb66-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">x1 =</span> x1,</span>
<span id="cb66-9"><a href="#cb66-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">x2 =</span> x2,</span>
<span id="cb66-10"><a href="#cb66-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">x3 =</span> x3)</span>
<span id="cb66-11"><a href="#cb66-11" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Generate one dataset and use <code>ggpairs</code> to show pair plots:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">400</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>sim_data <span class="ot">&lt;-</span> <span class="fu">simulate_data</span>(n)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(sim_data, <span class="at">progress =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notebook2_complete_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Step 1.</strong> Fit <code>lm(y ~ ., data = sim_data)</code> (every column as a predictor) and look at the coefficients with their intervals (<code>tidy</code>, then <code>ggcoef</code>). Before you look: which coefficients do you expect to be near zero?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># my_model &lt;- lm(____, data = sim_data)</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="co"># tidy(my_model, conf.int = TRUE) |&gt; knitr::kable(digits = 2)</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="co"># my_model |&gt; ggcoef()</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>...</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal solution">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-47-contents" aria-controls="callout-47" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-47" class="callout-47-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>my_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> ., <span class="at">data =</span> sim_data)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(my_model, <span class="at">conf.int =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">digits =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.62</td>
<td style="text-align: right;">0.12</td>
<td style="text-align: right;">5.16</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.38</td>
<td style="text-align: right;">0.85</td>
</tr>
<tr class="even">
<td style="text-align: left;">x1</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">58.34</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.96</td>
<td style="text-align: right;">1.03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">x2</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">-0.13</td>
<td style="text-align: right;">0.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">x3</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">-0.20</td>
<td style="text-align: right;">0.21</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>my_model <span class="sc">|&gt;</span> <span class="fu">ggcoef</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notebook2_complete_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<p><strong>Question 6.</strong> <code>x2</code> is in the true function, and its coefficient is close to zero (and <code>x3</code> is not in the truth). Why? Hint: what is the least-squares slope of <span class="math inline">\(2x_2 - x_2^2\)</span> on <span class="math inline">\(x_2\)</span> when <span class="math inline">\(x_2 \sim U(0, 2)\)</span>? Then plot the residuals against <code>x2</code> (<code>augment(my_model)</code> from <code>broom</code> gives a data frame with a <code>.resid</code> column). Would part 2’s diagnostics have caught this?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">augment</span>(my_model) <span class="sc">|&gt;</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(x2, .resid)) <span class="sc">+</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="notebook2_complete_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-48-contents" aria-controls="callout-48" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-48" class="callout-48-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Least squares fits the best <em>linear</em> approximation. For <span class="math inline">\(X \sim U(0, 2)\)</span>, <span class="math inline">\(\mathrm{Cov}(X, X^2)/\mathrm{Var}(X) = (2 - 1 \cdot 4/3)/(1/3) = 2\)</span>, so the population slope of <span class="math inline">\(2X - X^2\)</span> on <span class="math inline">\(X\)</span> is <span class="math inline">\(2 - 2 = 0\)</span>; the predictors are independent, so this is also the multiple-regression coefficient, and the fitted coefficient is near zero with a tight interval (at <span class="math inline">\(n = 400\)</span> the estimate is usually within <span class="math inline">\(\pm 0.15\)</span> of zero and the interval about <span class="math inline">\(\pm 0.2\)</span> wide; at <span class="math inline">\(n = 100\)</span> the same picture, noisier). The derivative <span class="math inline">\(2 - 2x_2\)</span> is <span class="math inline">\(+2\)</span> at one end and <span class="math inline">\(-2\)</span> at the other; the linear fit averages it away. <code>x3</code> is simply irrelevant. The residuals against <code>x2</code> show an inverted U: the class of planes does not contain <span class="math inline">\(f\)</span>, and a one-predictor residual plot does show it here, because the missing piece is a function of one input. A coefficient near zero with a tight interval is evidence of no <em>linear</em> signal, not of no effect.</p>
</div>
</div>
</div>
<section id="optional-can-be-done-at-home-2" class="level4">
<h4 class="anchored" data-anchor-id="optional-can-be-done-at-home-2">Optional, can be done at home</h4>
<!-- Not in the seminar. -->
<p><strong>Experiment.</strong> Repeat the steps above, making various choices: the number and distributions of predictor variables; the form of the true outcome generating function; the distribution of the noise (either just changing <code>sd</code> or using some other centered distribution); the sample size; the choice of fitted model (<code>poly(x2, 2)</code>?); which aspect of the model to interpret or check against the truth.</p>
<p><strong>Challenge</strong>: can you find some potential dangers of using regression models, where the model is wrong in some important way and our diagnostic methods fail to show us the problem? (A missing piece that depends on two inputs at once is a good place to start.)</p>
<p><strong>Challenge</strong>: what are some strengths or robustness properties of regression models that we should appreciate and trust in the long run? i.e.&nbsp;are there ways the model can be wrong but our conclusions from it will still (usually?) be good enough to use anyway?</p>
<div class="answer callout callout-style-default callout-tip callout-titled" title="Reveal answer">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-49-contents" aria-controls="callout-49" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Reveal answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-49" class="callout-49-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Danger: put an interaction or a product like <span class="math inline">\(x_1 x_2\)</span> into <code>f</code>; the coefficients on <code>x1</code> and <code>x2</code> are then slopes of a plane through a curved surface, and the one-predictor residual plots can look clean while the model is badly wrong along a diagonal. Strengths: when the truth is close to linear over the range of the data and <span class="math inline">\(n\)</span> is large relative to <span class="math inline">\(p\)</span>, the fitted plane is close to the best plane and its predictions inside that range are hard to beat; and even when the truth is curved there is a best plane, the one with the smallest risk among planes (the optimal model theorem with the minimization restricted to planes), and least squares estimates it. Sample least squares minimizes training error. Estimating the coefficients from finite data can leave its population risk above that of the best plane, by an amount the validation week measures.</p>
</div>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>