---
title: "Exercise set 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.retina = 3, warning = FALSE, message = FALSE)
library(tidyverse)
library(knitr)
theme_set(theme_minimal(base_size = 14))
```

## Causality

Choose one of the datasets analyzed in previous exercises, lectures, or seminars, and pick 2 or 3 variables in this dataset. You can also invent an unobserved variable that you believe might be important but is not included in the dataset. Using these variables:

-   Propose and draw a DAG that you believe to be importantly wrong compared to the real world, and explain why you think it does not accurately model the causal relationships that you believe to exist.

-   Propose and draw a DAG that you believe to be an improvement compared to the previous one. Comment in one or a few sentences why this second DAG is better, and also what you believe is its most important remaining weakness as a model for the real world causal relationships.

This is a conceptual exercise which would not be graded based on any kind of accuracy in relating to the real world, but only on your reasoning.

## ISLR Chapter 2, Section 2.4

Exercises 1 and 3

## ISLR Chapter 3, Section 3.6

Read the `R` lab, especially Sections 3.6.3-3.6.6

(You don't have to write anything about this, just be sure to read it)

## ISLR Chapter 3, Section 3.7

Exercises 1, 13, and 14


